---
- name: Build docker image Worker
  docker_image:
    build:
      path: "{{ worker_dir }}"
      pull: yes
    name: celery_worker
    source: build

- name: Get KLEE image from Docker Hub (this may take a while...)
  docker_image:
    name: klee/klee
    tag: latest
