---
- name: "Start {{ kleeweb_worker_container }} container"
  docker_container:
    name: "{{ kleeweb_worker_container }}"
    image: "{{ kleeweb_worker_container }}"
    restart_policy: always
    env:
      MAILGUN_API_KEY: "{{ mailgun_api_key if (mailgun_api_key is defined) else '' }}"
      AWS_ACCESS_KEY: "{{ aws_access_key if (aws_access_key is defined) else '' }}"
      AWS_SECRET_KEY: "{{ aws_secret_key if (aws_secret_key is defined) else '' }}"
      REDIS_HOST: "{{ redis_host }}"
      REDIS_PORT: "{{ redis_port | string }}"
      CELERY_BROKER_URL: "{{ celery_broker_url }}"
      DEVELOPMENT: "{{ '0' if (production is defined) else '1'}}"
    volumes:
      # To start other containers
      - /var/run/docker.sock:/var/run/docker.sock
      # For Klee to place results
      - /tmp/:/tmp/
    network_mode: "{{ 'host' if (ci) else 'bridge' }}"
    recreate: yes

- name: Create klee user for cronjob
  user: name=klee shell=/bin/bash groups=sudo
  when: not ci

- name: Add cronjob to restart worker on missed celery heartbeat
  cron:
    name: "Restart kleeweb-worker if celery heartbeat missed"
    minute: "30"
    job: 'if [ $(sudo docker logs kleeweb-worker &> ~/logs-kleeweb-worker.txt ; tail -1 ~/logs-kleeweb-worker.txt | grep "missed heartbeat from celery" | wc -l) -eq 1 ]; then $(sudo docker restart kleeweb-worker); fi'
    user: klee
  when: not ci
