---
- name: "Run {{ nginx_container }} container"
  docker_container:
    name: "{{ nginx_container }}"
    image: "{{ nginx_container }}"
    restart_policy: always
    networks:
      - name: "{{ container_network }}"
    ports:
      - "80:80"
    volumes:
      # For nginx to uWSGI's socket
      - /tmp:/tmp
    volumes_from:
      - "{{ kleeweb_container }}"
    recreate: yes
