---
- name: Run Docker nginx container
  docker_container:
    name: nginx-container
    image: nginx_image
    restart_policy: always
    networks:
      - name: "{{ container_network }}"
    ports:
      - "80:80"
    volumes:
      - /tmp:/tmp
      - /titb:/titb
    recreate: yes
