- hosts: all
  become: yes
  vars:
    pip_install_packages:
      - name: docker
  vars_files:
    - vars/common.yml
  roles:
    - role: geerlingguy.pip
      pip_package: python3-pip
    - role: geerlingguy.docker
      when: not ci
    - common

- hosts: master
  become: yes
  vars_files:
    - vars/common.yml
  vars:
    - production: no
  roles:
    - redis
    - db
    - web

- hosts: workers
  become: yes
  vars_files:
    - vars/development.yml
    - vars/common.yml
  roles:
    - worker

- hosts: testing
  become: yes
  roles:
    - e2e-tests
