- hosts: all
  become: yes
  vars:
    pip_install_packages:
      - name: docker
  pre_tasks:
    - name: apt-get update
      apt:
        update_cache: yes
  roles:
    - role: geerlingguy.pip
      pip_package: python3-pip
    - role: geerlingguy.docker
      when: not ci
    - common
    - env_files

- hosts: master
  become: yes
  roles:
    - redis
    - db
    - web

- hosts: workers
  become: yes
  roles:
    - worker
    - e2e-tests
