---
- name: "Build the {{ e2e_container }} container"
  docker_image:
    build:
      path: "{{ e2e_dir }}"
      pull: yes
    name: "{{ e2e_container }}"
    source: build

- name: "Start {{ e2e_container }} container"
  docker_container:
    name: "{{ e2e_container }}"
    image: "{{ e2e_container }}"
    env:
      WEBPAGE: "{{ main_webpage }}"
      ADMIN_PASSWORD: "{{ admin_password }}"
    network_mode: "{{ container_network }}"
    detach: no
    cleanup: yes

- name: "Build {{ worker_e2e_container }} container"
  docker_image:
    build:
      path: "{{ worker_dir }}"
      dockerfile: Dockerfile-tests
      pull: no
    name: "{{ worker_e2e_container }}"
    source: build

- name: "Start {{ worker_e2e_container }} container"
  docker_container:
    name: "{{ worker_e2e_container }}"
    image: "{{ worker_e2e_container }}"
    env:
      REDIS_HOST: "{{ redis_host }}"
      REDIS_PORT: "{{ redis_port | string }}"
      DEVELOPMENT: "1"
      # CELERY_BROKER_URL: "{{ celery_broker_url }}"
    volumes:
      # To start other containers
      - /var/run/docker.sock:/var/run/docker.sock
      # For Klee to place results
      - /tmp/:/tmp/
    network_mode: "{{ container_network }}"
    detach: no
    cleanup: yes

- name: Create klee user for cronjob
  user: name=klee shell=/bin/bash groups=sudo
  when: not ci

- name: Add cronjob for automated tests daily at 2pm
  cron:
    name: "Test Klee Web"
    minute: "0"
    hour: "14"
    job: "/src/python_runner.sh /usr/bin/python3 /titb/src/klee_web/tests/automated_e2e_tests.py"
    user: klee
  when: not ci
